- ui/ui_gtk.py
The function buffer_get_text expects the input value to be a buffer, not the get_text-method of some buffer.
> ui_gtk.py: bug fix in DB Editor, buffer_get_text

- pyglossary/plugins/stardict.py
- setup.py
there was no `import errno` which caused fatal error in `python2 setup.py install`.  anyway, checking for `os.path.exists` is better way to go.
> fixed critical installation error in setup.py

- pyglossary.pyw
- pyglossary/__init__.py
- pyglossary/glossary.py
- setup.py
firstly, logging was fixed.  it was necessary to reorder some parts of code inside `pyglossary.pyw` to make logger initialize as early as possible.  there's descriptive comment on lines 33-44.  other code except logger was just moved but not modified.
in order to allow `glossary.py` use logging, version number had been moved to `__init__.py`, because it is needed when parsing arguments; and parsing arguments needed to set up logger's verbosity.
maybe it would be good idea to move logger initializing routine to separate module in the future.
secondly, `class Glossary`:
- plugins loading becomes clean, separate functions.
- safety improved (by the use of `if hasattr()` and try-catch blocks), so broken plugin would be reported but not lead to crash.
- debug and errors logging normally.
- …
> important stability improvments

- pyglossary/plugins/appledict/_normalize.py
it's actually a bug of `BeautifulSoup + lxml`.  no other combinations appear to have same strange behaviour.
> appledict: fix dropping entries with one-letter title

- pyglossary.desktop
- pyglossary.spec
@ilius, I guess _Education_ is a more consistent value for the category.
> change Categories for pyglossary.desktop

- pyglossary/plugins/stardict.py
Export to startdict with filename not ending on .ifo resulted in
writing hidden files .ifo, .idx and .dict.
> Fix filenames without .ifo ending for startdict export

- setup.py
Hello, I've created a package (v3.2.1) and upload to PyPI.org, now that we can 'pip3 install pyglossary' on any system that with python pip installed.
this PR is the need change to create this package, also please refer to https://packaging.python.org/tutorials/packaging-projects/
and if you're interested in creating it yourself on new release, please tell me the account id of pypi.org and I'll add you as maintainer.
> update setup.py to adapt packaging with wheel.

- README.md
- pyglossary/plugins/appledict/templates/Makefile
The root may not be writable on newer Mac. Changing the README and Makefile to put dictionary development kit under `$HOME`
> Moving dictionary development kit to home

- pyglossary/plugins/ebook_kobo.py
Before this commit, multiple keywords for a single entry were just
joined with a pipe symbol. This is not what you want in a kobo
dictionary. This commit uses the first keyword as the headword for the
entry and adds the remaining ones as alternatives.
Open TODOs:
* ~~The kobo reader does not find the alternatives yet, although the
entries look good to me and the alternatives should be added to the
index.~~
* If the alternatives don't have the same prefix, they have to be
copied into each dicthtml file. This should probably be done as a
preprocessing step before sorting the dictionary.
> Kobo writer: additional keywords as alternatives

- pyglossary/plugins/dict_org.py
Hi,
This is a simple patch to make dictd contents look a bit well-formatted after parsing. The following are what I do in this PR:
1. Fix web link, so that any words with {} around will be rendered as `<a href=...>` link.
2. Replace newline with `<br />`.
Here are two screenshots (where I converted a dictd index file to aard slob). The first one is the original version, and the second one is my "patched" version:
It looks better after applying my patch:)
> Improve on parsing and rendering of dictd format

- pyglossary/core.py
Hello! 👋
The issue https://github.com/ilius/pyglossary/issues/307 hasn't been fixed properly.
The current code assumes pyglossary is always installed in "Python"/"Python{version}" directory ignoring cases when virtual env with custom directory name is used. For example, when I use [poetry](https://github.com/python-poetry/poetry), the directory is `c:\Users\germn\AppData\Local\pypoetry\Cache\virtualenvs\project-name-OPZUfFNv-py3.9\`.
This directory [can be fetched](https://stackoverflow.com/a/22004069/1113207) from `VIRTUAL_ENV` environment variable.
The PR adds a short fix for the case.
Note, that there's can be more convenient/proper way to do this, I didn't dig deep.
> Fix incorrect venv directory detection

- doc/octopus_mdict/README.rst
- pyglossary/html_utils.py
- pyglossary/plugins/dsl/__init__.py
- pyglossary/plugins/dsl/main.py
- pyglossary/plugins/jmdict.py
- pyglossary/plugins/octopus_mdict_new/__init__.py
- pyglossary/ui/main.py
- pyglossary/ui/ui_cmd_interactive.py
- pyglossary/ui/ui_gtk.py
There are small typos in:
- doc/octopus_mdict/README.rst
- pyglossary/html_utils.py
- pyglossary/plugins/dsl/__init__.py
- pyglossary/plugins/dsl/main.py
- pyglossary/plugins/jmdict.py
- pyglossary/plugins/octopus_mdict_new/__init__.py
- pyglossary/ui/main.py
- pyglossary/ui/ui_cmd_interactive.py
- pyglossary/ui/ui_gtk.py
Fixes:
- Should read `unescaping` rather than `unscaping`.
- Should read `formatted` rather than `formated`.
- Should read `understand` rather than `understan`.
- Should read `process` rather than `proccess`.
- Should read `object` rather than `objectt`.
- Should read `logging` rather than `loggging`.
- Should read `first` rather than `firsr`.
- Should read `except` rather than `execpt`.
- Should read `alternatives` rather than `altenatives`.
Semi-automated pull request …
> docs: Fix a few typos

- pyglossary/ebook_base.py
Function sortKey() was consistently being called with a list of strings. The method had been expecting a single byte-array
> Fix #351 - working epub and mobi destinations

- pyglossary/plugin_lib/readmdict.py
- pyglossary/text_utils.py
To prevent such warnings:
```python
pyglossary/plugin_lib/readmdict.py:139: DeprecationWarning: invalid escape sequence '\w'
taglist = re.findall(b'(\w+)="(.*?)"', header, re.DOTALL)
pyglossary/plugin_lib/readmdict.py:526: DeprecationWarning: invalid escape sequence '\d'
txt_list = re.split('`\d+`', txt)
pyglossary/text_utils.py:101: DeprecationWarning: invalid escape sequence '\|'
"""
```
> Fix DeprecationWarning: invalid escape sequence

- pyglossary/plugins/ebook_mobi.py
This will speed up conversion to mobi by skipping kindlegen's attempts to create an enhanced mobi (KF8), because Kindle dictionaries cannot be made in the KF8 format anyway. Kindlegen does automatically detect that it must create a mobi7 file, but not until after it's parsed some number of the source xhtml files listed in content.opf. This commit tells kindlegen to make a mobi7 file from the start.
> add mobi7-forcing switch to kindlegen command

- pyglossary/ui/ui_gtk.py
Based on https://discourse.gnome.org/t/get-screen-width-and-height/7245/13
Tested on Debian 11 (bullseye) with GNOME 3 Wayland. It should work on X11 too but I didn't test it.
Under my light usage, I didn't find anything else in the UI that needed changes under Wayland.
> ui_gtk: Fix getWorkAreaSize on Wayland

- pyglossary/plugin_lib/readmdict.py
I recently took some effort to understand the MDict 3.0 file format, as created by MdxBuilder 4.0 RC2. Now I update the readmdict module to support MDict 3.0 file format.
The description of the 3.0 format is under https://bitbucket.org/xwang/mdict-analysis.
> Update readmdict to support MDict V3 fomrat

- pyglossary/plugin_lib/readmdict.py
See comment https://github.com/ilius/pyglossary/pull/385#issuecomment-1253912058. MdxBuilder 4.0 RC2 and before creates files without UUID header. The encryption key derives from each data blocks's alder32 checksum.
> MDict: fix files created without UUID in header

- README.md
The ‘gnome.gobject-introspection’ alias was removed on 2022-01-13. Please use ‘pkgs.gobject-introspection’ directly.
> fix: README -> nixos command

- doc/p/appledict_bin.md
- plugins-meta/index.json
- pyglossary/plugins/appledict/__init__.py
- pyglossary/plugins/appledict_bin.py
Done in this PR:
* Simplify logic of finding filepath of `Body.data`
* This is data that we can extract from `Info.plist` file:
```json
{
"DCSDictionaryCSS": "DefaultStyle.css",
"CFBundleName": "English",
"DCSDictionaryUseSystemAppearance": true,
"IDXDictionaryIndexes": [
{
"IDXIndexSupportDataID": false,
"IDXIndexWritable": false,
"IDXIndexPath": "KeyText.index",
"IDXIndexAccessMethod": "com.apple.TrieAccessMethod",
"IDXIndexName": "DCSKeywordIndex",
"IDXIndexDataSizeLength": 2,
"IDXIndexBigEndian": false,
"TrieIndexCompressionType": 1,
"IDXIndexDataFields": {
"IDXFixedDataFields": [
{
"IDXDataFieldName": "DCSPrivateFlag",
"IDXDataSize": 2
}
],
"IDXExternalDataFields": [
{
"IDXDataFieldName": "DCSExternalBodyID",
"IDXDataSize": 8,
"IDXIndexName": "DCSBodyDataIndex"
}
], …
```
> extract AppleDict meta-info (langs, title, author)

- tests/g_appledict_bin_test.py
- tests/glossary_test.py
I added test files to https://github.com/soshial/pyglossary-test/tree/appledict-no-morph.
Could you please help making these tests run, @ilius?
1. How do I download whole dir instead of each file?
2. How to make paths point to the downloaded files? Now it points to `/Users/XXXX/Library/Caches/PyGlossary/test/appledict-bin/002-appledict-bin-no-morphology.dictionary`.
> Tests for AppleDict binary

- doc/pyicu.md
Debian uses the python3-icu package and ubuntu uses the pyicu package, per the docs https://gitlab.pyicu.org/main/pyicu#installing-pyicu and my experience with debain bullseye.
> Update pyicu docs for Debian

- pyglossary/plugins/appledict_bin/__init__.py
`DCSPrivateFlag` may be bigger than 0x20. Fixed that.
`DCSDictionaryLanguages` array inside plist file has a list of dictionaries inside this file
This DCSPrivateFlag per each article provides not only priority and parental control, but also a flag of translation direction:
* 0x0-0x1f values are reserved for the first language from the `DCSDictionaryLanguages` array
* 0x20-0x3f values are reserved for the second language etc.
> AppleDict-bin: fix crash for multidirectional dicts

- pyglossary/plugins/dsl/layer.py
- pyglossary/plugins/dsl/main.py
- pyglossary/plugins/dsl/tag.py
- tests/dsl_test.py
Thanks to a gentle and encouraging ping at [this thread](https://github.com/ilius/pyglossary/issues/487), I decided to take a look at how my old rusty code is doin'.
Needless to say, there's a lot of room for improvements — considering a jump from Python 2.7 at that time to 3.9+ nowadays.
Also, @ilius are you sure those `self: "typing.Self"` are really worth putting everywhere? I don't feel like they bring much value, and they cost a lot of visual noise. Actually, I've never seen these kind of hints.
> Improve Python typing in dsl plugin

- pyglossary/xdxf/transform.py
Sometimes the definition body lives inside a `<br></br>` pair, e.g.
```
<k>lexidium</k><br><b>lexĭdĭum</b>, <b>i</b>, <i>n.</i>, = leci/dion, <i>a little word</i>: lexidia colligere, Gell. 18, 7, 3.</br>
```
So perhaps it is a good idea to write the children of `<br>` as well?
> stardict xdxf: handle text within <br></br>

- pyglossary/os_utils.py
- pyglossary/plugins/stardict.py
- scripts/test-deps.sh
- tests/rundictzip_test.py
[izip](https://github.com/bauman/python-idzip/blob/master/setup.py) is maintained Python alternative to `dictzip` utility.
The pure python dependency instead of a binary, easy to obtain, no need to subprocess it.
- `dictzip` call replaced with `idzip`, while `runDictzip` contract are kept as close to `dictzip` version as possible.
- `stardict` writer compresses also a syn file when exists and `dictzip` opt is `True` for consistence.
- Few simple test cases for `runDictzip`.
`idzip` had been tried on the [DPD](https://digitalpalidictionary.github.io/) stardict. It does the job as same efficient as the `dictzip`, even a few percents faster. On a 1G random binary blob it shows a bit worse performance than `dictzip` do.
_P. S.:_ I will be out of a PC for a few next days, so sorry for possible …
> Replace dictzip with idzip

- pyglossary/ui/ui_web/index.html
- pyglossary/ui/ui_web/server_ws_http.py
- pyglossary/ui/ui_web/ui_controller.py
fixes #598
- add dialog for setting `convertOptions`, `readOptions` and `writeOptions` via JSON of the form
```json
{
"convertOptions": {
"sort": true,
"sortKeyName": "headword_lower:es_ES",
"sortEncoding": "utf-8",
"sqlite": true
},
"readOptions": {
"encoding": "utf-8",
"audio": true,
"example_color": "blue",
"abbrev": "hover"
},
"writeOptions": {
"compression": "zlib",
"content_type": "text/html; charset=utf-8",
"separate_alternates": true,
"word_title": true,
"version_info": false
}
}
```
> web ui: convert options dialog, fixes #598

- pyglossary/ui/ui_web/server_ws_http.py
Replace relative path for web root with `__file__.parent` dir or otherwise a 404 is thrown when webui is started from a different folder than the project root
> webui: fix 404 when not started from project root

- pyglossary/ui/ui_web/index.html
- fix wobbly scrolling on textarea update
- extract logging to method
> webui: fix textarea autoscroll

- setup.py
webui: add metadata to `setup.py` to include web_ui code and resources into the pip module.
> webui: add setup.py metadata

- pyglossary/plugins/aard2_slob/writer.py
For slob writer add `.opus`, `.oga` extensions for mime type `audio/ogg`
Reference:
- https://wiki.xiph.org/MIME_Types_and_File_Extensions#.opus_-_audio/ogg
Dictionaries containing ogg audio with `.opus` format are causing errors like below:
```ini
[ERROR] Aard2 slob: unknown content type for 'es/zenorio/sobredimensión.opus'
```
> slob writer: add opus, oga extensions

- pyglossary/plugins/ebook_mobi/writer.py
- `-dont_append_source` to create smaller files by not including source files in the final dict
- `-verbose` to help debug issues on failure
Closes #627.
Supersed #628.
> feat: more kindlgen arguments

- pyglossary/plugins/freedict/reader.py
Restores feature added in 40f00e3c that seems to have stopped working in 3e67672b.
Thanks to @karlb for pointing me in the right direction.
> freedict: fix adding inflections as keywords

- pyglossary/plugins/wiktextract/reader.py
- pyglossary/plugins/wiktextract/zh_utils.py
As a continuation of #637, here I implement list-style pronunciation section for Chinese (like in Wiktionary). 
This PR add a preprocessing script for Chinese entry which will be further develop for any Chinese-related fixes (or other languages as well). 
Example:
> Wiktextract: a more comprehesive list-style pronunciation section for Chinese entries

- pyglossary/plugins/wiktextract/zh_utils.py
A fix to #640. Some word e.g., (鿦)[https://en.wiktionary.org/wiki/%E9%BF%A6] have non-Unicode string `uie\x06` in it. 
This PR was tested on the entire Chinese Wiktionary so this should be sufficient for now.
Edit: also fixed some spelling
> Wiktionary: add handling for non-Unicode character 

- pyglossary/plugins/wiktextract/reader.py
- pyglossary/plugins/wiktextract/zh_utils.py
An improvement to #640 as discussed in #637.
> Wiktextract: Use `""` instead of `"_"` for fallback key in `zh_utils.py/processSound`

- pyglossary/ui/ui_tk.py
Screenshots are blurrier than in reality.
Before:
After:
> Update ui_tk.py (make app DPI-aware, remove blurry fonts on Windows)

- doc/p/__index__.md
- doc/p/yomichan.md
- plugins-meta/index.json
- pyglossary/plugin_handler.py
- pyglossary/plugins/yomichan/__init__.py
- pyglossary/plugins/yomichan/reader.py
- pyglossary/plugins/yomichan/types.py
I know that's maybe not a very requested feature but because I had a problem with converting my own collection of yomichan formatted dictionaries I wrote an plugin extension.
- Is there any possible way to properly implement progress bar if dictionary length is unknown until we read it fully?
- Are there any metadata (like `plugins-meta/index.json`) that also need to be updated? 
- I guess code style is differs from original code, isn't it? Any moments that I need to fix?
Supports only dictionaries of 3 version and don't implement any interactions with tags or kanji banks.
I haven't found a contribution guideline so if I have missed anything, please let me know.
Closes #622.
> Add Yomichan dictionaries reader

- pyglossary/plugins/quickdic6/writer.py
The `logger.warn()` method is deprecated since Python2.7 and replaced with `logger.warning()`. It leads to those warnings:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
> migrate to modern logger interface
