ilius/pyglossary

- pyglossary/plugins/dsl.py
- pyglossary/plugins/dsl/__init__.py
- pyglossary/plugins/dsl/perfect_dsl/__init__.py
- pyglossary/plugins/dsl/perfect_dsl/stash.py
- pyglossary/plugins/dsl/perfect_dsl/tests.py
gotta rewrite `PerfectDSLParser` from scratch soon to speed it up.  until then let it be here, as it just works.
`Stash` class name was inspired by `git-stash` command, hope i understand the word's meaning right. :)
> DSL plugin major improvements

- pyglossary/plugins/appledict/_dict.py
> appledict: check for BeautifulSoup version

- README.md
I just spotted it accidentally.
Just in case it helps.
> correcting small typo in README.md

- doc/non-gui_examples/stardict_sametypesequence.md
- pyglossary/plugins/stardict.py
Must be specified through --write-options.
> Add write support for Stardict with sametypesequence option

- pyglossary/plugins/appledict/templates/Dictionary.css
- pyglossary/plugins/appledict/templates/Makefile
1. add dark mode support for AppleDict output;
2. fix echo problem in Makefile of AppleDict.
> add dark mode support for AppleDict output

- pyglossary/plugins/freedict.py
This makes it easier to find inflected word when looking them up in
the dictionary.
> Freedict reader: Use inflections as keywords

- pyglossary/plugins/ebook_kobo.py
Fix support for alternates as explained in #232
@karlb Can you please review and test?
> Kobo: fix support for alternates: duplicate entries based on word prefix

- pyglossary/plugins/ebook_kobo.py
Fix the title issue @karlb mentioned in #238
Also did some refactoring.
@karlb Please review and test.
Also you may want to measure memory usage with `/usr/bin/time -v python3 main.py ...`
And let me know if it takes too much memory.
Thanks
> Kobo: refactor, show headword in title of alternate entries (#238)

- pyglossary/plugins/stardict.py
Stardict command line (sdcv) is very slow with large syn files, but has no problems with large .idx files (see discussion on   https://github.com/koreader/koreader/issues/5437 for details).  This patch adds a merge_syns option to the stardict writer to write the alternative words to the .idx file instead of the .syn file.
> Add merge_syns option to StarDict

- pyglossary/xdxf_transform.py
- Parse sr, gr, ex_orig, ex_transl tags and audio
- Use unicode symbols for audio and external link as placeholders
> Support sr, gr, ex_* and audio tags in XDXF

- pyglossary/plugins/cc_cedict/__init__.py
- pyglossary/plugins/cc_cedict/conv.py
> add CC-CEDICT option to use traditional for entry name

- pyglossary/plugins/octopus_mdict_new/__init__.py
Like words, they are decoded as utf-8.
> Decode mdict title & description if they're bytes

- pyglossary/entry_filters.py
- pyglossary/plugins/octopus_mdict_new/__init__.py
Treat `<div>` the same way `<p>` is treated.
> When remove HTML tags, also replace <div> with \n

- pyglossary/plugins/appledict_bin.py
> AppleDict binary: support different offsets

- pyglossary/plugins/appledict_bin/__init__.py
- pyglossary/plugins/appledict_bin/key_data.py
> AppleDict-bin: fix crash for Korean glossary

- pyglossary/plugins/appledict/__init__.py
- pyglossary/plugins/appledict/_content.py
- pyglossary/plugins/appledict/_dict.py
- pyglossary/plugins/appledict/_normalize.py
- pyglossary/plugins/appledict/indexes/__init__.py
- pyglossary/plugins/appledict/indexes/ru.py
- pyglossary/plugins/appledict/indexes/zh.py
- pyglossary/plugins/dsl/__init__.py
- pyglossary/plugins/dsl/layer.py
- pyglossary/plugins/dsl/main.py
- pyglossary/plugins/dsl/tag.py
- pyglossary/plugins/xdxf/__init__.py
- pyglossary/plugins/xdxf_lax.py
- pyglossary/xdxf.xsl
- tests/dsl_test.py
Contributors should use their real names in copyright statements, otherwise it has no legal power. Sorry about this childish mess.
> Update copyright name for ratijas

- pyglossary/ui/ui_gtk.py
- pyglossary/ui/ui_gtk4.py
Utilize the systems native file selector through portals.
https://docs.flatpak.org/en/latest/portals.html
> fix: unable to select files from within flatpak

- pyglossary/plugins/aard2_slob.py
According to this [discussion here](https://github.com/itkach/aard2-android/discussions/187#discussioncomment-10257912), we must set `uri` tag correctly.
> Slob: improve metadata & support bookmark migration

- doc/pyicu.md
replace broken link to PyICU with valid builds up to python 3.13
> fix broken pyicu link

- pyglossary/ui/ui_tk.py
- replace tix with ttk
- sorry for butching the interface, was looking for a quick fix, so it's slightly different from the original Tix UI.
...for the first time saw the tk interface on macos — for some reason it never worked with Tix, even with tk and Tix installed, with python 3.12
fixes #595
> fixes #595 remove tix
